name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your use case.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem does this feature solve? What are you trying to accomplish?
      placeholder: I'm trying to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work? Include API sketches if relevant.
      placeholder: |
        ```python
        # Example of the desired API
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered.
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the library does this relate to?
      options:
        - CSP Algebra
        - Semantics / LTS
        - Protocol Graph
        - Session Types (MPST)
        - Topology
        - Verification
        - Serialization
        - Documentation
        - Other
    validations:
      required: true
